pull_request_rules:
  - name: Automatic Merge (for Owner)
    conditions:
      - author=matejkosiarcik
      - assignee=matejkosiarcik
      - base=master
      - label!=work-in-progress
      - -title~=^.*((wip)|(WIP)|(Wip)).*$
      - -conflict
      - -merged
      - -locked
      - -draft
      - head~=^(develop|feature-.+)$
    actions:
      merge:
        method: merge
        strict: smart
        strict_method: rebase
