name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Set up QEMU ğŸ§©
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx ğŸ§©
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build ğŸ”§
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/amd64
          push: false
          tags: |
            matejkosiarcik/millipng:dev
