name: Build and Deploy

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4

      - name: Docker tags
        uses: docker/metadata-action@v3.5.0
        id: tags
        with:
          images: |
            matejkosiarcik/millipng
          tags: |
            type=raw,value=dev,enable=${{ github.event_name == 'push' }}
            type=raw,value=latest,enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}},enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'push tag' }}
            type=semver,pattern={{major}}.{{minor}}.{{patch}},enable=${{ github.event_name == 'push tag' }}

      - name: Set up QEMU ğŸ§©
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx ğŸ§©
        id: buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Docker tags
        run: echo ${{ steps.tags.outputs.tags }}

      - name: Login to DockerHub ğŸ”
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Publish ğŸ”§
        uses: docker/build-push-action@v2.7.0
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
